#!/bin/sh
# vim:tw=0:ts=2:sw=2:et:norl:nospell:ft=bash
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/DepoXy/depoxy#🍯
# License: MIT

source_deps () {
  # Load: debug, etc.
  command -v logger.sh > /dev/null && . logger.sh ||
    . "${SHOILERPLATE:-${HOME}/.kit/sh}/sh-logger/bin/logger.sh"

  # Load: link_hard.
  command -v link-hard.sh > /dev/null && . link-hard.sh ||
    . "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}/link-hard.sh"

  # Load: symlink_*, infuser_prepare, font_highlight.
  command -v overlay-symlink.sh > /dev/null && . overlay-symlink.sh ||
    . "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}/overlay-symlink.sh"

  # ***

  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  # Load: link_hard_dep*.
  . "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.kit/git/ohmyrepos/lib/my-deps-manage-shoilerplate.sh"

  # Load: _vendorfs_host_is_depoxy_client_id.
  . "${DEPOXYAMBERS_DIR:-${ambers_path}}/core/depoxy_fs.sh"

  # Load: _depoxy_print_homebrew_path.
  . "${DEPOXYAMBERS_DIR:-${ambers_path}}/core/brewskies.sh"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_private_fries_bashrc () {
  cd "${HOME}"

  # Symlink:          ${HOME}/.mrinfuse/.homefries/.bashrc-bin/bashrx.private.sh
  # (which is really: ${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers/home/.homefries/.bashrc-bin/bashrx.private.sh)
  #   from:           ${HOME}/.homefries/.bashrc-bin/bashrx.private.sh
  symlink_mrinfuse_file '.homefries/.bashrc-bin/bashrx.private.sh'
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_private_fries_home_convenience () {
  local before_cd="$(pwd -L)"
  cd "${HOMEFRIES_DIR:-${HOME}/.homefries}"

  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  symlink_overlay_file "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.gitconfig.local"

  # SPIKE/2023-02-28: I don't recall if this is merely a convenience, or
  # if it's actually wired.
  # - SPIKE: If just a convenience, remove this symlink.
  symlink_overlay_file "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.inputrc"

  cd "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

link_hard_dep_shoilerplate () {
  # Local directory is $HOME, just FYI. Run from Homefries's directory.
  local before_cd="$(pwd -L)"

  cd "${HOMEFRIES_DIR:-${HOME}/.homefries}"

  link_hard_dep_sh_colors

  link_hard_dep_sh_logger

  link_hard_dep_sh_pather

  link_hard_dep_sh_print_nanos_now

  link_hard_dep_sh_rm_safe

  cd "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_public_fries_dot_files () {
  local before_cd="$(pwd -L)"
  cd "${HOME}"

  # Symlink publib dotfiles top-level home-fries, at ~/.homefries/, e.g.,
  #   .homefries/.gitmux.conf
  #   .homefries/.profile
  #   .homefries/.tmux.conf.local
  # Oh, that's it.
  # See also:
  #   ll ~ | grep "home/"
  # to what's from WF, too, like
  #   .depoxy/ambers/home/.gitconfig.local
  # etc.

  # Instead of the find, see also 1-depth ls-files:
  #
  #   git ls-files | sed -E 's,.*/.*,,' | sed -E '/^\s*$/d'
  #
  # except includes symlinks.

  symlink_overlay_file ".homefries/.bashrc"

  # Look for home-fries home file paths.
  for hfhfpath in $(
    find "${HOMEFRIES_DIR:-${HOME}/.homefries}/" \
      -maxdepth 1 \
      -type f \
      ! -name "LICENSE" \
      ! -name "*README*" \
      ! -name ".gitignore" \
      ! -name ".ignore-example" \
  ); do
    # echo "${hfhfpath}"
    symlink_overlay_file "${hfhfpath}"
  done

  cd "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# Homefries defines a `bexit` command when you run `bash` from within
# a shell, so you can easily exit subshells but not the enclosing shell.
# - Generally, you can `be<TAB>` to auto-complete `bexit`, except
#   @macos Homebrew imagemagick installs `benchmark_xl`.
#   So `bex<TAB>`? I don't think so. Rename the conflict that we don't use.
# - At least I think it's from imagemagick:
#     /opt/homebrew/bin/benchmark_xl ->
#       /opt/homebrew/Cellar/jpeg-xl/0.7.0_1/bin/benchmark_xl
setup_homefries_bexit_deconflict_imagemagick_benchmark_xl () {
  local brew_bin="$(dirname "$(_depoxy_print_homebrew_path)")"

  local conflict="${brew_bin}/benchmark_xl"
  local renamed="${brew_bin}/jpeg-xl--benchmark_xl"

  if [ -f "${conflict}" ]; then
    /bin/mv "${conflict}" "${renamed}"

    info " Renamed offensive $(font_highlight "${conflict}") → $(font_highlight "${renamed}")"
  fi
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

main () {
  set -e

  source_deps

  [ "$(basename $0)" != "infuse-home-fries" ] || LOG_LEVEL=0

  # Set MR_REPO, say hello (emit $MR_REPO), and look for --switches.
  infuser_prepare "${HOME}" "$@"

  local before_cd="$(pwd -L)"
  cd "${MR_REPO}"

  setup_private_fries_bashrc

  setup_private_fries_home_convenience

  link_hard_dep_shoilerplate

  setup_public_fries_dot_files

  setup_homefries_bexit_deconflict_imagemagick_benchmark_xl

  cd "${before_cd}"
}

# Run the infuser iff being executed.
if ! $(printf %s "$0" | grep -q -E '(^-?|\/)(ba|da|fi|z)?sh$' -); then
  main "$@"
fi

unset -f main

