#!/bin/sh
# vim:tw=0:ts=2:sw=2:et:ai:ft=bash
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/DepoXy/depoxy#🍯
# License: MIT

# Setup core DepoXy Ambers into user name.

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

source_deps () {
  # Load: symlink_*, infuser_prepare.
  command -v overlay-symlink.sh > /dev/null && . overlay-symlink.sh ||
    . "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}/overlay-symlink.sh"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_myrepos_mrconfig_and_mrinfuse () {
  local ambers_home="$1"

  # First create the ~/.mrinfuse symlink, which is the basis for many
  # of the symlink_mrinfuse_file and symlink_mrinfuse_dir chores
  # that many projects use.
  symlink_overlay_dir "${ambers_home}" ".mrinfuse"

  # The ~/.depoxy/ambers/bin/macOS/install-ohmyrepos.sh installer
  # was probably the first to seed ~/.mrconfig, but just in case
  # the user skipped that script and is calling this script directly
  # (which I don't even know if that would work), or if that symlink
  # somehow got clobbered, we'll ensure it's wired correctly.
  # - That is, the $HOME infuse task in the '.mrconfig' file symlinked
  #   here is the task that invoked *us*, most likely. Circuitous!
  symlink_mrinfuse_file "_mrconfig" ".mrconfig"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_myrepos_generated_mrtrust () {
  local ambers_home="$1"

  # We setup ~/.mrtrust as a symlink to ~/.depoxy/ambers/home/.mrtrust,
  # though the latter file is generated and not stored in the repo.
  # (There's no requirement for this, it's just nice to keep assets
  # together in the same location so they're easy to find and view.)
  # Rather than call `ln -sf` directly, which doesn't care if the
  # source exists or not, we want to call symlink_mrinfuse_file, so
  # that its nicely formatted output is included in the output log.
  # As such, give the source a little poke to ensure it exists.
  touch "${ambers_home}/.mrtrust"
  symlink_mrinfuse_file ".mrtrust"

  m4 \
    --define=USER_HOME=${HOME} \
    --define=DOPP_KIT=${DOPP_KIT:-${HOME}/.kit} \
    --define=GITREPOSPATH=${GITREPOSPATH:-${HOME}/.kit/git} \
    "${ambers_home}/.mrtrust.m4" \
    > "${HOME}/.mrtrust"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

main () {
  local depoxy_root="$1"

  set -e

  source_deps

  [ "$(basename $0)" != "infuse-depoxy-ambers" ] || LOG_LEVEL=0

  local ambers_path="${depoxy_root}"
  local ambers_home="${depoxy_root}/home"
  if [ -z "${ambers_path}" ]; then
    ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"
    ambers_home="${DEPOXYAMBERS_DIR:-${ambers_path}}/home"
  fi

  # Set MR_REPO, say hello (emit $MR_REPO), and look for --switches.
  infuser_prepare "${HOME}" "$@"

  local before_cd="$(pwd -L)"
  cd ${MR_REPO}

  setup_myrepos_mrconfig_and_mrinfuse "${ambers_home}"

  setup_myrepos_generated_mrtrust "${ambers_home}"

  cd "${before_cd}"
}

# Run the infuser iff being executed.
if ! $(printf %s "$0" | grep -q -E '(^-?|\/)(ba|da|fi|z)?sh$' -); then
  main "$@"
fi

unset -f main

