#!/bin/sh
# vim:tw=0:ts=2:sw=2:et:norl:nospell:ft=bash
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/DepoXy/depoxy#🍯
# License: MIT

# MAYBE/2025-01-30 13:11: Move to nvim-depoxy?
# - Except for ~/.config/neovide overlay
SCRIPT_NAME="infuse-nvim-depoxy"

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

MSG_PREFIX_ADDED_SYMLINKS_DIR='Created symlinks for'

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

source_deps () {
  local omr_lib="${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}"

  local shlogg_dir="${omr_lib}/../deps/sh-logger/bin"

  # HSTRY/2025-01-07: Rather than rely on PATH (you can `. <filename>`
  # and the shell will search PATH for a match) like author's code has
  # mostly done in the past, new approach: The sourced files assume
  # they're sourced from their own directory, so they can find
  # dependencies relative to the current working directory. Also
  # by using the full path when sourcing, we don't have to worry about
  # same-named filename clashes (e.g., avoid sourcing *some other*
  # "logger.sh" on PATH).
  local before_cd="$(pwd -L)"

  cd -- "${shlogg_dir}"
  # Load: warn, etc.
  . "${shlogg_dir}/logger.sh"

  cd -- "${omr_lib}"
  # Load: link_hard
  . "${omr_lib}/link-hard.sh"
  # Load: link_private_exclude
  . "${omr_lib}/link-private-exclude.sh"
  # Load: link_private_ignore, link_private_ignore_
  . "${omr_lib}/link-private-ignore.sh"
  # Load: symlink_*, infuser_prepare, font_highlight
  . "${omr_lib}/overlay-symlink.sh"

  cd -- "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

seed_myrepos_mrconfig_dubs_vim () {
  local before_cd="$(pwd -L)"

  # CXREF: ~/.kit/nvim/.mrconfig — loaded via 'chain = true'
  symlink_overlay_file "nvim-depoxy/mrconfig/_mrconfig" ".mrconfig"

  # ***

  cd -- "${nvim_repos}/nvim-depoxy"

  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  # CXREF: ~/.depoxy/ambers/home/.kit/nvim/_mrconfig
  symlink_overlay_file "${ambers_path}/home/.kit/nvim/_mrconfig" "mrconfig/depoxy-mrconfig"

  # USAGE: Optional private DepoXy Client Vim projects.
  # - Place at either ~/.depoxy/running/home/.kit/nvim/_mrconfig-private-nvim
  #   Or at           ~/.depoxy/ambers/home/.kit/nvim/_mrconfig-private-nvim
  local vim_conf_private="home/.kit/nvim/_mrconfig-private-nvim"
  local private_conf
  for private_conf in \
    "${DEPOXYDIR_STINTS_FULL}/${DEPOXY_CLIENT_ID}/${vim_conf_private}" \
    "${ambers_path}/${vim_conf_private}" \
  ; do
    if [ -f "${private_conf}" ]; then
      symlink_overlay_file "${private_conf}" "mrconfig/$(basename -- "${vim_conf_private}")"

      break
    fi
  done

  cd -- "${before_cd}"
}

# ***

seed_myrepos_mrinfuse_dubs_vim_plug () {
  # CXREF: ~/.kit/nvim/.mrinfuse
  symlink_overlay_dir "nvim-depoxy/mrinfuse" ".mrinfuse"
}

# ***

setup_private_git_exclude () {
  local before_cd="$(pwd -L)"

  cd -- "${nvim_repos}/nvim-depoxy"

  # Place ~/.kit/nvim/nvim-depoxy/.gitignore.local
  #         → ~/.kit/nvim/nvim-depoxy/.git/info/exclude
  #           → ~/.depoxy/ambers/home/.kit/nvim/_git/info/exclude
  MR_REPO="$(pwd -L)" link_private_exclude

  cd -- "${before_cd}"
}

# ***

setup_vim_plugs_fdignore () {
  # CXREF: ~/.kit/nvim/.fdignore
  # ALTLY: But uses full path:
  #   MR_REPO="${nvim_repos}" symlink_mrinfuse_file "_fdignore" ".fdignore"
  symlink_overlay_file "nvim-depoxy/mrinfuse/_fdignore" ".fdignore"
}

# ***

# Place ~/.kit/nvim/.gitignore
setup_kit_nvim_git_exclude () {
  # MAYBE/2023-11-11: Make `link_hard_mrinfuse_file`, akin to `symlink_mrinfuse_file`.
  # - This hard-links .gitignore (sorta like `link_private_exclude`, except that
  #   function hard-links .git/info/exclude).
  # - A `link_hard_mrinfuse_file` would let us simplify the args, e.g.,
  #     link_hard_mrinfuse_file "plugs/.gitignore"
  link_hard "${nvim_repos}/nvim-depoxy/mrinfuse/_gitignore" "${nvim_repos}/.gitignore"
}

# ***

# Place ~/.kit/nvim/.ignore
setup_kit_nvim_grep_ignore () {
  # CXREF: ~/.kit/nvim/.ignore
  # ALTLY: But uses full path:
  #   MR_REPO="${nvim_repos}" link_private_ignore "_ignore"
  symlink_overlay_file "nvim-depoxy/mrinfuse/_ignore" ".ignore"
}

# ***

# Place ~/.kit/nvim/nvim-depoxy/.ignore
setup_private_grep_ignore () {
  local before_cd="$(pwd -L)"

  cd -- "${nvim_repos}/nvim-depoxy"

  link_private_ignore_

  cd -- "${before_cd}"
}

# ***

# CXREF:
# ~/.depoxy/ambers/home/.kit/nvim/nvim-depoxy/.config/nvim/lua/config/profile-client.lua

setup_nvim_depoxy_lua_profile () {
  local before_cd="$(pwd -L)"

  cd -- "${nvim_repos}/nvim-depoxy"

  MR_REPO="$(pwd -L)" symlink_mrinfuse_file ".config/nvim/lua/config/profile-client.lua"

  cd -- "${before_cd}"
}

# ***

# CXREF:
# ~/.depoxy/ambers/home/.kit/nvim/nvim-depoxy/.config/nvim/lua/specs/group--depoxy-client.lua

setup_nvim_depoxy_lua_specs () {
  local before_cd="$(pwd -L)"

  cd -- "${nvim_repos}/nvim-depoxy"

  MR_REPO="$(pwd -L)" symlink_mrinfuse_file ".config/nvim/lua/specs/group--depoxy-client.lua"

  cd -- "${before_cd}"
}

# ***

# Link ~/.config/<target>/ → ~/.depoxy/ambers/home/.config/<target>/
wire_dot_config () {
  local dir="$1"

  local before_cd="$(pwd -L)"

  cd -- "${HOME}"

  MR_REPO="$(pwd -L)" symlink_mrinfuse_dir ".config/${dir}"

  cd -- "${before_cd}"
}

# ***

# Link ~/.vimrc → ~/.depoxy/ambers/home/.vim/.vimrc
#      ~/.vim/.vimrc →  "      "     "    "     "
#      ~/.vim/autoload → ~/.depoxy/ambers/home/.vim/autoload
wire_dot_vimrc_and_autoload () {
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"
  local dxyambs_dir="${DEPOXYAMBERS_DIR:-${ambers_path}}"

  local before_cd="$(pwd -L)"

  cd -- "${HOME}"

  symlink_overlay_dir "${nvim_repos}/nvim-depoxy/.vim" ".vim"

  # This is for convenience, so you don't have to use `vim -u`.
  symlink_overlay_file "${nvim_repos}/nvim-depoxy/.vim/.vimrc" ".vimrc"
  # # Also add ~/.vim/.vimrc, for convenience and history.
  # symlink_overlay_file "${dxyambs_dir}/home/.vim/.vimrc" ".vim/.vimrc"

  # symlink_overlay_dir "${dxyambs_dir}/home/.vim/autoload" ".vim/autoload"

  # Currently, autoload/plug.vim is symlink to deps/ file in same project.
  # - ALTLY: This is more tightly coupled (uses inter-project path):
  #     symlink_overlay_file "${nvim_repos}/junegunn/start/vim-plug/plug.vim" \
  #       ".vim/autoload/plug.vim"

  cd -- "${before_cd}"
}

# ***

infuse_this_infuser () {
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  symlink_overlay_file "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/infuse-nvim-depoxy" "infuse"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

populate_run_generator () {
  # E.g., .mrinfuse/plugs/landonb/dubs_project_tray/generate_links.sh
  local generator="$1"

  local symldir
  symldir="$(dirname -- "${generator}")"

  if ! [ -f "${generator}" ]; then
    # Possible on very first infuse, before ~/.vim/.mrconfig* wired (that
    # is, user must `mr clone`-`mr infuse`-`mr clone`-`mr infuse`!).

    warn "Missing symlink generator: $(font_highlight "${generator}")"
    warn "- Please run \`mr -d / clone\` again, then re-infuse"

    return 0
  fi

  info "Running symlink generator: $(font_highlight "$(realpath -- "${generator}")") …"

  ${generator} > /dev/null

  info " ${MSG_PREFIX_ADDED_SYMLINKS_DIR} $(font_highlight "${symldir}/")"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# ISOFF/2024-12-05: dubs_file_finder is now deprecated in favor of
# junegunn/fzf.vim and DepoXy's vim-depoxy:
#   ~/.kit/nvim/junegunn/start/fzf.vim/README.md
#   ~/.kit/nvim/DepoXy/start/vim-depoxy/plugin/fzf-config.vim
# - You can still find dubs_file_finder under opt/:
#   ~/.kit/nvim/landonb/.whilom/dubs_file_finder

# CXREF:
#   ~/.kit/nvim/landonb/.whilom/dubs_file_finder/plugin/dubs_file_finder.vim
setup_private_plug_file_dubs_file_finder () {
  # Unexpected, because no longer called from main().
  >&2 echo "ISOFF: dubs_file_finder is disabled! Skipping generator: cmdt_paths/"

  return 1

  # ***

  local dff_dir="${nvim_repos}/landonb/dubs_file_finder"

  if ! [ -d "${dff_dir}" ]; then
    dff_dir="${nvim_repos}/landonb/.whilom/dubs_file_finder"
  fi

  if ! [ -d "${dff_dir}" ]; then

    return 0
  fi

  # ***

  local before_cd="$(pwd -L)"

  cd -- "${dff_dir}"

  # HSTRY/2024-05-08: Previously used generate_links.sh at
  #   ~/.depoxy/ambers/home/.vim/cmdt_paths/
  # to populate a custom find-file project, and infuse would
  # symlink that path:
  #
  #   symlink_overlay_dir "${HOME}/.vim/.mrinfuse/cmdt_paths"
  #
  # But now we just use the uber project under ~/.projlns

  # CXREF:
  #   ~/.depoxy/ambers/home/.projlns/infuse-projlns-core.sh
  local dxy_projlns="${DEPOXY_PROJLNS:-${HOME}/.projlns}"
  local dxy_deeplns="${DEPOXY_PROJLNS_DEPOXY:-${dxy_projlns}/depoxy-deeplinks}"

  # SAVVY: rg ignores .ignore rule from same directory as target if
  # that target would create a file system loop, e.g.,:
  #
  #   rg: File system loop found:
  #     /home/user/.projlns/depoxy-deeplinks/home/user/_vim/plugs/landonb/.whilom/dubs_file_finder/cmdt_paths
  #   points to an ancestor
  #     /home/user/.projlns/depoxy-deeplinks
  #
  # So put cmdt_paths 1 deep.
  mkdir -p "_cmdt_paths"
  cd -- "_cmdt_paths"

  symlink_overlay_dir "${dxy_deeplns}" "cmdt_paths"

  cd -- "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# dubs_cuts is searched on #9 search (aka #9 grep aka #9 grep-steady).

populate_dubs_cuts_generate () {
  # MEH/2019-10-27: This infuser takes a hot second to run (possibly
  # because I could not make the script POSIX-compliant, or more likely
  # because of the for-loop on find with regex).

  # Run this Dubs Vim dubs_cuts generator manually, i.e., execute:
  #   ~/.kit/nvim/nvim-depoxy/mrinfuse/landonb/dubs_project_tray/generate_links.sh
  # to populate:
  #   ~/.depoxy/ambers/home/.kit/nvim/landonb/dubs_project_tray/dubs_cuts/
  # upon which
  #   setup_private_plug_file_dubs_project_tray_symlink_dubs_cuts
  # depends.
  local generator
  MR_REPO="${nvim_repos}" \
    generator="$(path_to_mrinfuse_resolve "landonb/dubs_project_tray/generate_links.sh")"
  populate_run_generator "${generator}"
}

# ***

setup_private_plug_file_dubs_project_tray_symlink_dubs_cuts () {
  # Unexpected, because no longer called from main().
  >&2 echo "ISOFF: dubs_project_tray/dubs_cuts generator is disabled!"

  return 1

  # ***

  local plug_dir="${nvim_repos}/landonb/dubs_project_tray"

  [ -d "${plug_dir}" ] || return 0

  local before_cd="$(pwd -L)"

  cd -- "${plug_dir}"

  # Creates:
  #   ~/.kit/nvim/landonb/dubs_project_tray/dubs_cuts
  # ALTLY:
  #   symlink_overlay_dir \
  #     "${HOME}/.depoxy/running/home/.kit/nvim/landonb/dubs_project_tray/dubs_cuts"
  MR_REPO="$(pwd -L)" symlink_mrinfuse_dir "dubs_cuts"

  cd -- "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_project_plug_vim_depoxy () {
  local depoxy_vim_org="DepoXy"

  local depoxy_vim_start="${nvim_repos}/${depoxy_vim_org}/start"

  mkdir -p "${depoxy_vim_start}"

  local before_cd="$(pwd -L)"

  # ***

  cd -- "${depoxy_vim_start}/vim-depoxy/plugin"

  local fzf_vim="${DOPP_KIT:-${HOME}/.kit}/go/fzf/plugin/fzf.vim"

  if [ -e "${fzf_vim}" ]; then
    symlink_overlay_file "${fzf_vim}" "fzf.vim"
  fi

  # ***

  cd -- "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_project_plug_vim_landonb () {
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  local landonb_vim_org="landonb"

  mkdir -p "${nvim_repos}/${landonb_vim_org}"

  local before_cd="$(pwd -L)"

  # ***

  cd -- "${nvim_repos}/${landonb_vim_org}"

  # ALTLY:
  #   symlink_overlay_file \
  #     "${nvim_repos}/nvim-depoxy/mrinfuse/${landonb_vim_org}/_ignore" \
  #     ".ignore"
  MR_REPO="${nvim_repos}/${landonb_vim_org}" link_private_ignore_

  # ***

  cd -- "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_private_coc_config () {

  # FIXME/2025-01-30: Revisit this; disabling now because switched to Neovim.
  return 0

  symlink_mrinfuse_file "coc-settings.json"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# REFER: Run Vim without vimrc, run :Helptags, run :quit:
#          -c {command}    Execute {command}
# - SAVVY: Uses pathogen plug's :Helptags command,
#   so must load vimrc, i.e., not: `vim -u NONE ...`
# - SAVVY: Vim complains when not wired for tty, e.g.,
#     Vim: Warning: Output is not to a terminal
#     Vim: Warning: Input is not from a terminal
#   So ignore stderr.
# - SAVVY: If there's an error with this call, we
#   won't know, because it's `echom`'d within Vim
#   and won't be captured on stdout.
setup_vim_generate_helptags () {
  info "Rebuilding Vim helptags: $(font_highlight "call pathogen#helptags()")"

  # TRYNG/2025-01-30: It shouldn't matter if you call Vim or
  # Neovim because either way it builds 'tags' files.
  # - SAVVY: However, `nvim` appears to run the command
  #   and exit, regardless of startup `echom`, whereas
  #   Vim will await user confirmation is there's any
  #   blather during startup.
  DXY_INFUSE_VIM_BUILD_HELPTAGS_VIM=${DXY_INFUSE_VIM_BUILD_HELPTAGS_VIM:-false}

  # SAVVY: Print newline in case Vim prompts on startup...
  # - Note that a Vim startup prompt happens if there are
  #   `echom` messages during startup. Which generally
  #   shouldn't happen, but they might. And if they do,
  #   they could hang the 'infuse' process until the
  #   user interacts with the prompt (which they might not
  #   realize they need to do, because stderr inhibited).
  # ALTLY: `vim -c "Helptags" -c q`, but this call ensures you won't
  # confuse pathogen's :Helptags with Vim's built-in :helptags <dir>
  if ${DXY_INFUSE_VIM_BUILD_HELPTAGS_VIM:-false} || ! command -v nvim >/dev/null; then
    printf "\n" | vim -c ":call pathogen#helptags()" -c q 2> /dev/null
  else
    nvim -c ":call pathogen#helptags()" -c q >/dev/null 2>&1
  fi
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

main () {
  set -e

  local nvim_repos="${NEOVIM_REPOS:-${DOPP_KIT:-${HOME}/.kit}/nvim}"

  # Unset MR_CONFIG so that the OMR/lib source_deps fcns run.
  MR_CONFIG= source_deps

  if [ "$(basename -- "$0")" = "${SCRIPT_NAME}" ]; then
    LOG_LEVEL=${MR_LOG_LEVEL:-${LOG_LEVEL_VVVERBOSE:-0}}
  else
    LOG_LEVEL=${MR_LOG_LEVEL:-${LOG_LEVEL_TRACE:-10}}
  fi

  # Set MR_REPO, say hello (emit $MR_REPO), and look for --switches.
  infuser_prepare "${nvim_repos}" "$@"

  local before_cd="$(pwd -L)"
  cd -- "${MR_REPO}"

  # ***

  seed_myrepos_mrconfig_dubs_vim

  seed_myrepos_mrinfuse_dubs_vim_plug

  setup_private_git_exclude

  setup_vim_plugs_fdignore

  setup_kit_nvim_git_exclude

  setup_kit_nvim_grep_ignore

  setup_private_grep_ignore

  setup_nvim_depoxy_lua_profile

  setup_nvim_depoxy_lua_specs

  wire_dot_config "nvim"

  wire_dot_config "neovide"

  # ISOFF/2025-02-24: Eh. Seems like a distraction to
  # demo different Neovim configs!
  #
  #  wire_dot_config "nvim-Lazyman"

  # USAGE: Isolated Neovim environments:
  #   NVIM_APPNAME=nvim_dxy nvim
  #   NVIM_APPNAME=nvim_lzy nvim
  wire_dot_config "nvim_depoxy"
  wire_dot_config "nvim_lazyb"

  wire_dot_vimrc_and_autoload

  infuse_this_infuser

  # ***

  # ISOFF/2025-01-31: But keeping for findabilty re: any remaining
  # cmdt_paths/ paths.
  #
  #   setup_private_plug_file_dubs_file_finder

  # ***

  setup_project_plug_vim_depoxy

  setup_project_plug_vim_landonb

  # ***

  # Setup Coc's config.

  setup_private_coc_config

  # ***

  setup_vim_generate_helptags

  # ***

  # ISOFF/2025-02-01: Takes a few seconds, and the directory listing
  # isn't very useful.
  # - Would otherwise populate:
  #   ~/.depoxy/running/home/.kit/nvim/landonb/dubs_project_tray/dubs_cuts/
  #
  #   # It might take a few-ten secs to populate
  #   #   ~/.depoxy/ambers/home/.kit/nvim/landonb/dubs_project_tray/dubs_cuts/
  #   # so call last, to make debugging previous calls quicker.
  #   populate_dubs_cuts_generate
  #   setup_private_plug_file_dubs_project_tray_symlink_dubs_cuts

  # ***

  cd -- "${before_cd}"
}

# Run the infuser iff being executed.
if [ "$(basename -- "$(realpath -- "$0")")" = "${SCRIPT_NAME}" ]; then
  main "$@"
fi

unset -f main

