#!/bin/sh
# vim:tw=0:ts=2:sw=2:et:norl:nospell:ft=bash
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/DepoXy/depoxy#🍯
# License: MIT

if [ -z "$1" ]; then
  mr -d / infuse
else
  mr -d "$1" -n infuse
fi

