#!/bin/sh
# vim:tw=0:ts=2:sw=2:et:ai:ft=bash
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/DepoXy/depoxy#🍯
# License: MIT

# Setup core DepoXy Ambers into user name.

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

source_deps () {
  # Load: warn, etc.
  command -v logger.sh > /dev/null && . logger.sh ||
    . "${SHOILERPLATE:-${HOME}/.kit/sh}/sh-logger/bin/logger.sh"

  # Load: symlink_*, infuser_prepare.
  command -v overlay-symlink.sh > /dev/null && . overlay-symlink.sh ||
    . "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}/overlay-symlink.sh"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_myrepos_mrconfig_and_mrinfuse () {
  # First create the ~/.mrinfuse symlink, which is the basis for many
  # of the symlink_mrinfuse_file and symlink_mrinfuse_dir chores
  # that many projects use.
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"
  symlink_overlay_dir "${DEPOXYAMBERS_DIR:-${ambers_path}}/home" '.mrinfuse'

  # The ~/.depoxy/ambers/bin/macOS/install-ohmyrepos.sh installer
  # was probably the first to seed ~/.mrconfig, but just in case
  # the user skipped that script and is calling this script directly
  # (which I don't even know if that would work), or if that symlink
  # somehow got clobbered, we'll ensure it's wired correctly.
  # - That is, the $HOME infuse task in the '.mrconfig' file symlinked
  #   here is the task that invoked *us*, most likely. Circuitous!
  symlink_mrinfuse_file "_mrconfig" ".mrconfig"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_myrepos_generated_mrtrust () {
  # We setup ~/.mrtrust as a symlink to ~/.depoxy/ambers/home/.mrtrust,
  # though the latter file is generated and not stored in the repo.
  # (There's no requirement for this, it's just nice to keep assets
  # together in the same location so they're easy to find and view.)
  # Rather than call `ln -sf` directly, which doesn't care if the
  # source exists or not, we want to call symlink_mrinfuse_file, so
  # that its nicely formatted output is included in the output log.
  # As such, give the source a little poke to ensure it exists.
  touch "${DEPOXYAMBERS_DIR}/home/.mrtrust"
  symlink_mrinfuse_file ".mrtrust"

  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"
  m4 \
    --define=USER_HOME=${HOME} \
    --define=DOPP_KIT=${DOPP_KIT:-${HOME}/.kit} \
    --define=GITREPOSPATH=${GITREPOSPATH:-${HOME}/.kit/git} \
    ${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.mrtrust.m4 \
    > ${HOME}/.mrtrust
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_private_infuse_symlinks_ohmyrepos_lib () {
  local omr_bin="${OHMYREPOS_DIR:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos}/bin"

  local before_cd="$(pwd -L)"

  cd "${omr_bin}"

  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"
  local home_cfg_root="${DEPOXYAMBERS_DIR:-${ambers_path}}/home"

  # Symlinks for your DEV convenience.
  symlink_overlay_file "${home_cfg_root}/infuse"
  symlink_overlay_file "${home_cfg_root}/infuse-depoxy-ambers"
  symlink_overlay_file "${home_cfg_root}/infuse-dubs-vim"
  symlink_overlay_file "${home_cfg_root}/infuse-home-fries"
  symlink_overlay_file "${home_cfg_root}/infuse-platform-macOS"
  symlink_overlay_file "${home_cfg_root}/infuse-user-home"

  # Somewhat related. Sorta somewhat.
  symlink_overlay_file \
    "${home_cfg_root}/.kit/git/ohmyrepos/bin/js-npm-patch-opn-sensible-open"

  cd "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

main () {
  set -e

  source_deps

  [ "$(basename $0)" != "infuse-depoxy-ambers" ] || LOG_LEVEL=0

  # Set MR_REPO, say hello (emit $MR_REPO), and look for --switches.
  infuser_prepare "${HOME}" "$@"

  local before_cd="$(pwd -L)"
  cd ${MR_REPO}

  setup_myrepos_mrconfig_and_mrinfuse

  setup_myrepos_generated_mrtrust

  setup_private_infuse_symlinks_ohmyrepos_lib

  cd "${before_cd}"
}

# Run the infuser iff being executed.
if ! $(printf %s "$0" | grep -q -E '(^-?|\/)(ba|da|fi|z)?sh$' -); then
  main "$@"
fi

unset -f main

