#!/bin/sh
# vim:tw=0:ts=2:sw=2:et:norl:nospell:ft=bash
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/DepoXy/depoxy#🍯
# License: MIT

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

MSG_PREFIX_ADDED_SYMLINKS_DIR='Created symlinks for'

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

source_deps () {
  # HSTRY/2025-01-07: Rather than rely on PATH (you can `. <filename>`
  # and the shell will search PATH for a match) like author's code has
  # mostly done in the past, new approach: The sourced files assume
  # they're sourced from their own directory, so they can find
  # dependencies relative to the current working directory. Also
  # by using the full path when sourcing, we don't have to worry about
  # same-named filename clashes (e.g., avoid sourcing *some other*
  # "logger.sh" on PATH).
  local before_cd="$(pwd -L)"

  cd -- "${SHOILERPLATE:-${HOME}/.kit/sh}/sh-logger/bin"
  # Load: warn, etc.
  . "${SHOILERPLATE:-${HOME}/.kit/sh}/sh-logger/bin/logger.sh"

  cd -- "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}"
  # Load: link_hard
  . "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}/link-hard.sh"
  # Load: link_private_exclude
  . "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}/link-private-exclude.sh"
  # Load: link_private_ignore, link_private_ignore_
  . "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}/link-private-ignore.sh"
  # Load: symlink_*, infuser_prepare, font_highlight
  . "${OHMYREPOS_LIB:-${GITREPOSPATH:-${HOME}/.kit/git}/ohmyrepos/lib}/overlay-symlink.sh"

  cd -- "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

seed_myrepos_mrconfig_dubs_vim () {
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  # CXREF: This is usually redundant because ~/.mrinfuse:
  #   ~/.depoxy/ambers/home/infuse-config-omr
  #     setup_myrepos_mrconfig_and_mrinfuse
  # but it makes for shorter symlinks.
  # - SAVVY: Create descendency link if you symlinked
  #     ~/.mrinfuse -> ~/.depoxy/running/home
  #   E.g.,
  #     ln -sfn ~/.depoxy/ambers/home/.vim ~/.depoxy/running/home/.vim/.mrinfuse
  symlink_overlay_dir "../${MRT_INFUSE_DIR:-.mrinfuse}/.vim" "${MRT_INFUSE_DIR:-.mrinfuse}"

  symlink_mrinfuse_file "_mrconfig" ".mrconfig"
  symlink_mrinfuse_file "_mrconfig-dubs" ".mrconfig-dubs"
  symlink_mrinfuse_file "_mrconfig-3rdp" ".mrconfig-3rdp"
  symlink_mrinfuse_file "_mrconfig-lsp" ".mrconfig-lsp"

  local vim_conf_private="home/.vim/_mrconfig-private"

  # USAGE: Optional private DepoXy Client Vim projects.
  # - Place at either ~/.depoxy/running/home/.vim/_mrconfig-private
  #   Or at           ~/.depoxy/ambers/home/.vim/_mrconfig-private
  local private_conf
  for private_conf in \
    "${ambers_path}/${vim_conf_private}" \
    "${DEPOXYDIR_STINTS_FULL}/${DEPOXY_CLIENT_ID}/${vim_conf_private}" \
  ; do
    if [ -f "${private_conf}" ]; then
      symlink_mrinfuse_file "${private_conf}" ".mrconfig-private"

      break
    fi
  done
}

# ***

seed_myrepos_mrinfuse_dubs_vim_plug () {
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  symlink_overlay_dir "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.vim/plugs" "plugs/.mrinfuse"
}

# ***

setup_private_git_exclude () {
  # Place ~/.vim/.gitignore.local
  #     → ~/.vim/.git/info/exclude
  #     → home/.vim/_git/info/exclude
  link_private_exclude
}

# ***

setup_vim_plugs_fdignore () {
  local before_cd="$(pwd -L)"

  cd "${HOME}/.vim/plugs"

  # Use path relative to MR_REPO=~/.vim
  symlink_mrinfuse_file "plugs/_fdignore" "plugs/.fdignore"

  cd "${before_cd}"
}

# ***

# Place ~/.vim/plugs/.gitignore.
setup_vim_plugs_git_exclude () {
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  # MAYBE/2023-11-11: Make `link_hard_mrinfuse_file`, akin to `symlink_mrinfuse_file`.
  # - This hard-links .gitignore (sorta like `link_private_exclude`, except that
  #   function hard-links .git/info/exclude).
  # - A `link_hard_mrinfuse_file` would let us simplify the args, e.g.,
  #     link_hard_mrinfuse_file "plugs/.gitignore"
  link_hard "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.vim/plugs/_gitignore" "plugs/.gitignore"
}

# ***

setup_vim_plugs_grep_ignore () {
  local before_cd="$(pwd -L)"

  cd "${HOME}/.vim/plugs"

  # Use path relative to MR_REPO=~/.vim
  link_private_ignore "plugs/_ignore"

  cd "${before_cd}"
}

# ***

setup_private_grep_ignore () {
  # Place ~/.vim/.ignore.
  link_private_ignore_
}

# ***

# Link ~/.config/<target>/ → ~/.depoxy/ambers/home/.config/<target>/
wire_dot_config () {
  local dir="$1"

  local before_cd="$(pwd -L)"

  cd "${HOME}"

  MR_REPO="$(pwd -L)" symlink_mrinfuse_dir ".config/${dir}"

  cd "${before_cd}"
}

# ***

# Link ~/.vimrc → ~/.vim/.vimrc
wire_home_vimrc () {
  local before_cd="$(pwd -L)"

  cd "${HOME}"

  symlink_overlay_file ".vim/.vimrc" ".vimrc"

  cd "${before_cd}"
}

# ***

infuse_this_infuser () {
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  symlink_overlay_file "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/infuse-dubs-vim" "infuse"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

populate_run_generator () {
  # E.g., .mrinfuse/plugs/landonb/start/dubs_project_tray/generate_links.sh
  local generator="$1"

  local symldir
  symldir="$(dirname -- "${generator}")"

  if ! [ -f "${generator}" ]; then
    # Possible on very first infuse, before ~/.vim/.mrconfig* wired (that
    # is, user must `mr clone`-`mr infuse`-`mr clone`-`mr infuse`!).

    warn "Missing symlink generator: $(font_highlight "${generator}")"
    warn "- Please run \`mr -d / clone\` again, then re-infuse"

    return 0
  fi

  info "Running symlink generator: $(font_highlight "${generator}")…"

  ${generator} > /dev/null

  info " ${MSG_PREFIX_ADDED_SYMLINKS_DIR} $(font_highlight "${symldir}/")"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# ISOFF/2024-12-05: dubs_file_finder is now deprecated in favor of
# junegunn/fzf.vim and DepoXy's vim-depoxy:
#   ~/.vim/plugs/junegunn/start/fzf.vim/README.md
#   ~/.vim/plugs/DepoXy/start/vim-depoxy/plugin/fzf-config.vim
# - You can still find dubs_file_finder under opt/:
#   ~/.vim/plugs/landonb/opt/dubs_file_finder

# CXREF:
#   ~/.vim/plugs/landonb/opt/dubs_file_finder/plugin/dubs_file_finder.vim
setup_private_plug_file_dubs_file_finder () {
  local dff_dir="${HOME}/.vim/plugs/landonb/start/dubs_file_finder"

  if ! [ -d "${dff_dir}" ]; then
    dff_dir="${HOME}/.vim/plugs/landonb/opt/dubs_file_finder"
  fi

  if ! [ -d "${dff_dir}" ]; then

    return 0
  fi

  # ***

  local before_cd="$(pwd -L)"

  cd "${dff_dir}"

  # HSTRY/2024-05-08: Previously used generate_links.sh at
  #   ~/.depoxy/ambers/home/.vim/cmdt_paths/
  # to populate a custom find-file project, and infuse would
  # symlink that path:
  #
  #   symlink_overlay_dir "${HOME}/.vim/.mrinfuse/cmdt_paths"
  #
  # But now we just use the uber project under ~/.projlns

  # CXREF:
  #   ~/.depoxy/ambers/home/.projlns/infuse-projlns-core.sh
  local dxy_projlns="${DEPOXY_PROJLNS:-${HOME}/.projlns}"
  local dxy_deeplns="${DEPOXY_PROJLNS_DEPOXY:-${dxy_projlns}/depoxy-deeplinks}"

  # SAVVY: rg ignores .ignore rule from same directory as target if
  # that target would create a file system loop, e.g.,:
  #
  #   rg: File system loop found:
  #     /home/user/.projlns/depoxy-deeplinks/home/user/_vim/plugs/landonb/opt/dubs_file_finder/cmdt_paths
  #   points to an ancestor /home/user/.projlns/depoxy-deeplinks
  #
  # So put cmdt_paths 1 deep.
  mkdir -p "_cmdt_paths"
  cd "_cmdt_paths"

  symlink_overlay_dir "${dxy_deeplns}" "cmdt_paths"

  cd "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# dubs_cuts is searched on #9 search (aka #9 grep aka #9 grep-steady).

populate_dubs_cuts_generate () {
  # MEH/2019-10-27: This infuser takes a hot second to run (possibly
  # because I could not make the script POSIX-compliant, or more likely
  # because of the for-loop on find with regex).

  # Run the Dubs Vim dubs_cuts infuser, i.e., execute:
  #   ~/.depoxy/ambers/home/.vim/plugs/landonb/start/dubs_project_tray/generate_links.sh
  # to populate:
  #   ~/.depoxy/ambers/home/.vim/plugs/landonb/start/dubs_project_tray/dubs_cuts/
  # aka:
  #  "${HOME}/.vim/.mrinfuse/plugs/landonb/start/dubs_project_tray/dubs_cuts"
  # upon which setup_private_plug_file_dubs_project_tray_symlink_dubs_cuts
  # depends.
  local generator
  generator="$(path_to_mrinfuse_resolve "plugs/landonb/start/dubs_project_tray/generate_links.sh")"
  populate_run_generator "${generator}"
}

# ***

setup_private_plug_file_dubs_project_tray_symlink_dubs_cuts () {
  [ -d "${HOME}/.vim/plugs/landonb/start/dubs_project_tray" ] || return 0

  local before_cd="$(pwd -L)"

  cd "${HOME}/.vim/plugs/landonb/start/dubs_project_tray"

  # symlink_overlay_dir "${HOME}/.vim/.mrinfuse/plugs/landonb/start/dubs_project_tray/dubs_cuts"
  MR_REPO="$(pwd -L)" symlink_mrinfuse_dir "dubs_cuts"

  cd "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_project_plug_vim_depoxy () {
  local depoxy_vim_org="DepoXy"

  local depoxy_vim_start="${HOME}/.vim/plugs/${depoxy_vim_org}/start"

  mkdir -p "${depoxy_vim_start}"

  local before_cd="$(pwd -L)"

  # ***

  cd "${depoxy_vim_start}/vim-depoxy/plugin"

  local fzf_vim="${DOPP_KIT:-${HOME}/.kit}/go/fzf/plugin/fzf.vim"

  if [ -e "${fzf_vim}" ]; then
    symlink_overlay_file "${fzf_vim}" "fzf.vim"
  fi

  # ***

  cd "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_project_plug_vim_landonb () {
  local ambers_path="${DEPOXYDIR_BASE_FULL:-${HOME}/.depoxy}/ambers"

  local landonb_vim_org="landonb"

  mkdir -p "${HOME}/.vim/plugs/${landonb_vim_org}"

  local before_cd="$(pwd -L)"

  # ***

  cd "${HOME}/.vim/plugs/${landonb_vim_org}"

  symlink_overlay_file \
    "${DEPOXYAMBERS_DIR:-${ambers_path}}/home/.vim/plugs/${landonb_vim_org}/_ignore" \
    ".ignore"

  # ***

  cd "${before_cd}"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_private_coc_config () {
  symlink_mrinfuse_file "coc-settings.json"
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# REFER: Run Vim without vimrc, run :Helptags, run :quit:
#          -c {command}    Execute {command}
# - SAVVY: Uses pathogen plug's :Helptags command,
#   so must load vimrc, i.e., not: `vim -u NONE ...`
# - SAVVY: Vim complains when not wired for tty, e.g.,
#     Vim: Warning: Output is not to a terminal
#     Vim: Warning: Input is not from a terminal
#   So ignore stderr.
# - SAVVY: If there's an error with this call, we
#   won't know, because it's `echom`'d within Vim
#   and won't be captured on stdout.
setup_vim_generate_helptags () {
  info "Rebuilding Vim helptags: $(font_highlight "call pathogen#helptags()")"
  # SAVVY: Print newline in case Vim prompts on startup...
  # - Note that a Vim startup prompt happens if there are
  #   `echom` messages during startup. Which generally
  #   shouldn't happen, but they might. And if they do,
  #   they could hang the 'infuse' process until the
  #   user interacts with the prompt (which they might not
  #   realize they need to do, because stderr inhibited).
  # ALTLY: `vim -c "Helptags" -c q`, but this call ensures you won't
  # confuse pathogen's :Helptags with Vim's built-in :helptags <dir>
  printf "\n" | vim -c ":call pathogen#helptags()" -c q 2> /dev/null
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

main () {
  set -e

  # Unset MR_CONFIG so that the OMR/lib source_deps fcns run.
  MR_CONFIG= source_deps

  if [ "$(basename -- "$0")" = "infuse-dubs-vim" ]; then
    LOG_LEVEL=${MR_LOG_LEVEL:-${LOG_LEVEL_VVVERBOSE:-0}}
  else
    LOG_LEVEL=${MR_LOG_LEVEL:-${LOG_LEVEL_TRACE:-10}}
  fi

  # Set MR_REPO, say hello (emit $MR_REPO), and look for --switches.
  infuser_prepare "${HOME}/.vim" "$@"

  local before_cd="$(pwd -L)"
  cd "${MR_REPO}"

  # ***

  seed_myrepos_mrconfig_dubs_vim

  seed_myrepos_mrinfuse_dubs_vim_plug

  setup_private_git_exclude

  setup_vim_plugs_fdignore

  setup_vim_plugs_git_exclude

  setup_vim_plugs_grep_ignore

  setup_private_grep_ignore

  wire_dot_config "nvim"

  wire_dot_config "neovide"

  wire_home_vimrc

  infuse_this_infuser

  # ***

  setup_private_plug_file_dubs_file_finder

  # ***

  setup_project_plug_vim_depoxy

  setup_project_plug_vim_landonb

  # ***

  # Setup Coc's config.

  setup_private_coc_config

  # ***

  setup_vim_generate_helptags

  # ***

  # It might take a few-ten secs to populate
  #   ~/.depoxy/ambers/home/.vim/plugs/landonb/start/dubs_project_tray/dubs_cuts/
  # so call last, to make debugging previous calls quicker.
  populate_dubs_cuts_generate
  setup_private_plug_file_dubs_project_tray_symlink_dubs_cuts

  # ***

  cd "${before_cd}"
}

# Run the infuser iff being executed.
SCRIPT_NAME="infuse-dubs-vim"
if [ "$(basename -- "$(realpath -- "$0")")" = "${SCRIPT_NAME}" ]; then
  main "$@"
fi

unset -f main

