#!/bin/sh
# vim:tw=0:ts=2:sw=2:et:norl:ft=bash

# USAGE: Call this script from a Karabiner-Elements rule.

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

main () {
  [ -f "${HOME}/.config/depoxy/depoxyrc" ] && . "${HOME}/.config/depoxy/depoxyrc"

  # Open, e.g., ~/.kit/txt/emoji-lookup/emoji-lookup.rst
  # - CXREF: ~/.kit/sh/gvim-open-kindness/bin/gvim-open-kindness
  "${SHOILERPLATE:-${DOPP_KIT:-${HOME}/.kit}/sh}/gvim-open-kindness/bin/gvim-open-kindness" \
    "${DOPP_KIT:-${HOME}/.kit}/txt/emoji-lookup/emoji-lookup.rst"
}

# Run the function iff being executed.
SCRIPT_NAME="gvim-open--Unicode-Emojis"
if [ "$(basename -- "$(realpath -- "$0")")" = "${SCRIPT_NAME}" ]; then
  main "$@"
fi

